name: Deploy to AWS S3
description: Deploy a static website to AWS S3
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
    # bio-gha-hosting
    #  ap-northeast-1
  bucket-region:
    description: 'S3 bucket region'
    required: false
    default: 'ap-northeast-1'
  dist-folder:
    description: 'Folder containing the static website files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
